services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Indiquer le Dockerfile pour l'application FastAPI
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama  # Indiquer le Dockerfile pour Ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
